# Generated by Django 5.1.2 on 2024-10-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugaipunt', '0002_jugador_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='num_federat',
            field=models.IntegerField(default=0),
        ),
    ]
